AWSTemplateFormatVersion: '2010-09-09'
Description: Security Group para instancias EC2 y ALB

Resources:
  MinticSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso HTTP y SSH
      VpcId: !ImportValue MinticVPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH access
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP access
      Tags:
        - Key: Name
          Value: MinticSecurityGroup

Outputs:
  SecurityGroupId:
    Description: ID del Security Group
    Value: !Ref MinticSecurityGroup
    Export:
      Name: MinticSecurity-SG